### ISSUE TITLE
recover_F_from_E_K function calculator

### ISSUE THREAD

**Issue by roadcode** [Easonyesheng/A2PM-MESA#4]
Essential and fundamental matrices relation: F = K<sub>1</sub><sup>-T</sup> EK<sub>0</sub><sup>-1</sup>  
while in the recover_F_from_E_K  function, the fundamental matrices is calculated by 
```python
F = np.matmul(np.matmul(K1.T, E), K0)
```
 can you explain why
if K0 and K1 is not given, can we use findFundamentalMat to calculate F?

**Comment by Easonyesheng** [comment]
HI~ It's a typo and we have fixed it. (This code is only used in a re-factored version of gam.)
Yes, if you use gam, F is achieved without Ks.

**Comment by roadcode** [comment]
I use a2pm_mesa_egam_dkm_scannet.yaml config.
just use this code
```python
F = cv2.findFundamentalMat(np.array(temp_corrs)[:, :2], np.array(temp_corrs)[:, 2:])
```
replace egam.py 658-659 line to calculate fundamental matrices, is that right?
And another question, any plan to add the warpper for single image pair matching? :smiley:

**Comment by Easonyesheng** [comment]
Sure, it’s right.
The single image warpper will be added in a mouth, pls stay tuned.🫡
